#!/usr/bin/env bash
#Script that displays the time for 12 hours and 59 minutes: display hours from 0 to 12 display minutes from 1 to 59
h=0; while [ $h -le 12 ]; do x=1; case $x in 1) echo "Hour: $h"; esac; while [ $x -le 59 ]; do echo "$x"; x=$((x+1)); done; h=$((h+1)); done
