#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements.
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.
#The checker is running on Docker, so make sure to read this(https://web.archive.org/web/20171117023601/http://blog.jonathanargentiero.com/docker-sed-cannot-rename-etcsedl8ysxl-device-or-resource-busy/)
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/g ~/hosts.new
echo "8.8.8.8       facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
